
name: flutter_oauth_example
description: Demonstrates how to use the flutter_oauth plugin.

dependencies:
  flutter:
    sdk: flutter
  flutter_oauth:
    path: ../

flutter:
  uses-material-design: true