name: flutter_oauth
description: A flutter oauth package for performing oauth operations
version: 0.0.4
author: Joe Birch <hitherejoebirch@googlemail.com>
homepage: https://github.com/hitherejoe/FlutterOAuth

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  url_launcher: ^4.0.3

dev_dependencies:

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.5.6 <2.0.0"

flutter:
